
language: python
python:
 - 3.4
script:
 - python3 test_planet.py
deploy:
- provider: s3
  local_dir: dist
  access_key_id: AKIAT5Z6X2M5MPQQ4WXO
  secret_access_key: Dv3xyLsNcG39VqNZXNEReHG0HpNF+mKCyoQwC5xIeGk01lXJIlsFws4VRKGbREHSBRy7xhHuaBQtVW3qm/uFAZbZkX936lb1agsiy2rUPpktkObsJinf6FIwDZuZ3gk5eN0zwmCCCr1CvxxstROoyvTc/7DOnw8D8EGNJnRtVj43rd9bc+fX13Dqs6TIWUsYnkZlOJVvSKvdWQrciaNZCWnsPWiis/fkryIrMtO07LXCPUem/YQw0kS5vsr0ijojlPX1bqp3IvDrKTfwzqokgUt3iL7buKjEhPJjn6UlcJyVF0ym//7AWV9guNtuZ0iHK7OWGPmdz0emRTh/Y6701GpQJgNTMGznpHh5Kjp1nmZtHapTOuGRJgz0QNM4I3kWgT6eXP+hi+C9W6Rlo5/BdAiJOcDwW+6Vutwp0Eav8B/mG1igEh39PaizjG6LlYKtBBj2FuOlBzTqX0rWwg0PJOvgC0M8qWbZxyBk2Ha78/sDgPgY+ScvY+chxxptV2rS9dGq/n0t0Qa1VKNJtMpKkQ2fhgk2CV7mqGo2/Swf2D/OX9M1/ULTATywcZBF3i7L6WoeHicKbUjX5Uty8ApJkcYmL5kfP1LKrKkubj1mreVoGDUe5F5epww7WxivypzIx0xPp3i3MeHF1rCOaFN07GyBev72dUyuzoyvr/643lc=
  bucket: travis-deploy-summer
  region: ap-northeast-1
  skip_cleanup: true
 
