
language: python
python:
 - 3.4
script:
 - python3 test_planet.py
deploy:
- provider: s3
  local_dir: dist
  access_key_id: AKIAT5Z6X2M5MPQQ4WXO
  secret_access_key: 
    secure: "H4jumk7WU0Y03sLYfcZTIv6BAqzNcCXqFTuN/mYFa4YxntYzjE/DwuXefa8orsAWmBB/q9aQbUu1C87bT8y8ELtStMkED3q/BgHloaNzXvOlwwl2pvvt1Ta3eZEJ7QKLUe+biEMSF675pj9dx0Mys7XIJ/YBduBho2y7mRiC4TXtGJEtyKGvm4tHHtuXBu59qKJsx88Hy9Xs6IwE8eUyoHNBmqias1R0jdgT2W/G2PyKJvbpIcvdsEbja0EhkINnQ7NNwxYcRY7SS+ijCKx+50U2UrCPJx10GL1PBkT+n/FTYeREh1zCoVYo13zdQNXE9ja7XOsqHLlRA2Q95xQQDvranr/3pYLSnuQt24ni5IQuH01wrl2pNKorbHvHiC3wyw1cHAVN/CIhR7ULo8ZdvTTcd4zL8RZXVW1x8GNuDTpvsM5TyoIRykEfbBhe0ihpbXY/nmznGRpf3GyjRPWX3KUoTgXcTE8DtBUASCqQJxMkak6011J/mtOGBDQcHLwe1NlnOm48eMH4EMBZaD8XLNFgIeROxKubYno+y4st2vh219xZbE+Zs8M+vgjm4bh0DhJmYgpyDeR39a+8uLvjEKKfuCKGAkllt9uJ/vd5ObVAPXqYR346Fs+3ehUhL0+684Xbd40KmsTjj0UPlor/Ak7/GSd72ThrnkIiI7pkk/s="
  bucket: travis-deploy-summer
  region: ap-northeast-1
  skip_cleanup: true
 
