
language: python
python:
 - 3.4
script:
 - python3 test_planet.py
deploy:
- provider: s3
  local_dir: dist
  access_key_id: AKIAT5Z6X2M5MPQQ4WXO
  secret_access_key: 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
  bucket: travis-deploy-summer
  region: ap-northeast-1
  skip_cleanup: true
 
